create table if not exists wms.certificados_calidad (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null default 1,
  fecha_recibo date,
  codigo_material text,
  descripcion_material text,
  unidad_medida text,
  lote_proveedor text,
  fecha_fabricacion date,
  fecha_vencimiento date,
  cantidad numeric,
  proveedor text,
  documento text,
  orden_compra text,
  recibo_serial text,
  recibo_item text,
  estado_certificado text not null default 'PENDIENTE',
  certificado_nombre text,
  certificado_tipo text,
  certificado_data_url text,
  recibo_documento_html text,
  vence_gestion_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_certificados_calidad_empresa_fecha
  on wms.certificados_calidad (empresa_id, fecha_recibo desc);

create index if not exists idx_certificados_calidad_lote
  on wms.certificados_calidad (empresa_id, lote_proveedor);

create index if not exists idx_certificados_calidad_estado
  on wms.certificados_calidad (empresa_id, estado_certificado);

grant select, insert, update, delete on wms.certificados_calidad to anon, authenticated;
grant usage, select on sequence wms.certificados_calidad_id_seq to anon, authenticated;
