-- Análisis de inventario guardados (snapshot con fecha/hora).
create table if not exists wms.analisis_inventario (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null default 1,
  nombre text,
  archivo text,
  creado_por text,
  fecha timestamptz not null default now(),
  total_materiales integer default 0,
  total_faltantes integer default 0,
  total_sobrantes integer default 0,
  total_cuadrados integer default 0,
  datos jsonb not null default '[]'::jsonb
);

create index if not exists idx_analisis_inventario_empresa
  on wms.analisis_inventario (empresa_id, fecha desc);
